config/routes.rb
Rails.application.routes.draw do


  resources :reviews
  resources :events  do
    resources :event_attacments
  end
  resources :managers
  resources :dynamic_pages
  resources :dynamic_project_pages
  resources :project_attacments
  resources :project_category_attacments
  resources :static_pages
  mount Ckeditor::Engine => '/ckeditor'
  resources :post_categories, only: [:show] do
    resources :posts, only: [:show]
  end

  resources :project_categories 
  resources :projects
 
  resources :questions, only: [:create]
  resources :projects  do
    resources :managers
  end
  resources :managers_projects
  resources :projects  do
    resources :project_application_mails
  end


  patch '/projects/:id/project_info_mail' => 'projects#project_info_mail'


  root 'static#home'

  get '/administrator/dashboard', as: 'user_root'

  get 'persons/profile'



 devise_for :users, controllers: { sessions: "users/sessions" }
  
  namespace :administrator do
    resources :projects
    resources :questions
    resources :managers
    resources :project_categories
    resources :post_categories
    resources :posts
    resources :site_variables
    resources :dynamic_project_pages
    resources :static_pages
    resources :events
    resources :managers_projects
    resources :project_application_mails


    resources :menus
    resources :menu_items

    resources :sliders
    resources :slides

    resources :reviews
    resources :banners

   
  end

 
  get '/administrator', to: 'administrator#dashboard'
  get '/contacts', to: 'static#contacts'

  get '/company_info', to: 'static#company_info'
  get '/peoples', to: 'static#peoples'
  get '/partners', to: 'static#partners'
  get '/reviews', to: 'static#reviews'
  get '/free_tour', to: 'static#free_tour'

  get '/our_projects', to: 'static#our_projects'

  get '/import_projects', to: 'administrator/import#import_projects'
  get '/import_articles', to: 'administrator/import#import_articles'

  get '/delete_import_projects', to: 'administrator/import#delete_import_projects'
  get '/delete_import_articles', to: 'administrator/import#delete_import_articles'


  #get '/search', to: 'project#search'
  match "/search" => "projects#search", via: [ :get, :post, :patch, :delete ]
  

  get '/administrator/blocks_in_header', to: 'administrator/site_variables#blocks_in_header'
  get '/administrator/blocks_in_footer', to: 'administrator/site_variables#blocks_in_footer'
  get '/administrator/page_contact', to: 'administrator/site_variables#page_contact'
  get '/administrator/page_company_info', to: 'administrator/site_variables#page_company_info'
  get '/administrator/page_delivery_pay', to: 'administrator/site_variables#page_delivery_pay'

  get '/administrator/page_home', to: 'administrator/site_variables#page_home'

  



match "/404" => "application#errors_404", via: [ :get, :post, :patch, :delete ]




end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
	has_many :site_variables
end

app/controllers/administrator/banners_controller.rb
class Administrator::BannersController < AdministratorController
  
   before_action :set_menu, only: [:show, :edit, :update, :destroy]

  def index
    @banners = Banner.all
    render 'administrator/banners/index'
  end

  def edit
    @banner = Banner.find(params[:id])
    render 'administrator/banners/edit'
    end

    def new
    @banner = Banner.new
    
    end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.create(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to '/administrator/banners', notice: 'Product category was successfully created.' }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to '/administrator/banners', notice: 'Product category was successfully updated.' }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.jso

  private

  def banner_params
      params.require(:banner).permit(:image, :title, :link)
  end

  def set_menu
      @banner = Banner.find(params[:id])
    end

end

app/controllers/administrator/dynamic_project_pages_controller.rb
class Administrator::DynamicProjectPagesController < AdministratorController
  
   before_action :set_dynamic_project_page, only: [:show, :edit, :update, :destroy]

  def index
    @dynamic_project_pages = DynamicProjectPage.all.paginate(:page => params[:page], :per_page => 10)
  end

  def edit
    @dynamic_project_page = DynamicProjectPage.find(params[:id])
    render 'administrator/dynamic_project_pages/edit'
    end

    def new
    @dynamic_project_page = DynamicProjectPage.new
    
    end

  # POST /dynamic_project_pages
  # POST /dynamic_project_pages.json
  def create
    @dynamic_project_page = DynamicProjectPage.create(dynamic_project_page_params)

    respond_to do |format|
      if @dynamic_project_page.save
        format.html { redirect_to '/administrator/dynamic_project_pages', notice: 'Информация обновлена' }
        format.json { render :show, status: :created, location: @dynamic_project_page }
      else
        format.html { render :new }
        format.json { render json: @dynamic_project_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dynamic_project_pages/1
  # PATCH/PUT /dynamic_project_pages/1.json
  def update
    respond_to do |format|
      if @dynamic_project_page.update(dynamic_project_page_params)
        format.html { redirect_to '/administrator/dynamic_project_pages', notice: 'Информация обновлена' }
        format.json { render :show, status: :ok, location: @dynamic_project_page }
      else
        format.html { render :edit }
        format.json { render json: @dynamic_project_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dynamic_project_pages/1
  # DELETE /dynamic_project_pages/1.json
  def destroy
    @dynamic_project_page.destroy
    respond_to do |format|
      format.html { redirect_to '/administrator/dynamic_project_pages', notice: 'Информация обновлена' }
      format.json { head :no_content }
    end
  end

  private

  def dynamic_project_page_params
      params.require(:dynamic_project_page).permit(:title, :description, :query, :project_category_id, :meta_title, :meta_description, :meta_keywords, :slug)
  end

  def set_dynamic_project_page
      @dynamic_project_page = DynamicProjectPage.friendly.find(params[:id])
    end

end

app/controllers/administrator/events_controller.rb
class Administrator::EventsController < AdministratorController

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all.paginate(:page => params[:page], :per_page => 10)
  end 

  def new
    @event = Event.new()
  end

  def create
    @event = Event.new(event_params)
    @event.assign_attributes(event_params)
   
    respond_to do |format|
      if @event.save
        if params[:images] != nil
          params[:images].each do |image|
            EventAttacment.create(event_id: @event.id, image: image)
          end
        end

        format.html { redirect_to :back , notice: 'Информация обновлена' }
        format.json { render :index, status: :ok, location: @event }
      else
        format.html { render :update, notice: 'Произошла ошибка' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
    @event = Event.find(params[:id])
    @event_attachments = EventAttacment.where(event_id: @event.id)
  end

  def update
    @event = Event.find(params[:id])
    @event.assign_attributes(event_params)
   
    respond_to do |format|
      if @event.save
        if params[:images] != nil
          params[:images].each do |image|
            EventAttacment.create(event_id: @event.id, image: image)
          end
        end

        format.html { redirect_to :back , notice: 'Информация обновлена' }
        format.json { render :index, status: :ok, location: @event }
      else
        format.html { render :update, notice: 'Произошла ошибка' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to '/administrator/events', notice: 'Информация удалена' }
      format.json { head :no_content }
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :avatar, :lead, :date)
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/controllers/administrator/managers_controller.rb
class Administrator::ManagersController < AdministratorController
  
   before_action :set_manager, only: [:show, :edit, :update, :destroy]

  def index
    @managers = Manager.all
    render 'administrator/managers/index'
  end

  def edit
    @manager = Manager.find(params[:id])
    render 'administrator/managers/edit'
    end

    def new
    @manager = Manager.new
    render 'administrator/managers/new'
    end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.create(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to '/administrator/managers', notice: 'Product category was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to '/administrator/managers', notice: 'Product category was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

   def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Информация обновлена' }
      format.json { head :no_content }
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.jso

  private

  def manager_params
      params.require(:manager).permit(:name, :description, :languages, :skype, :avatar, :email, :phone, :elect, :company_info )
  end

  def set_manager
      @manager = Manager.find(params[:id])
    end

end

app/controllers/administrator/menu_items_controller.rb
class Administrator::MenuItemsController < AdministratorController
  
   before_action :set_menu, only: [:show, :edit, :update, :destroy]

  def index
    @menu_items = MenuItem.all
    render 'administrator/menus/index'
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
    @menus = Menu.all
    
  end

    def new
    @menu_item = MenuItem.new
    
    end

  # POST /menus
  # POST /menus.json
  def create
    @menu_item = MenuItem.create(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to '/administrator/menus', notice: 'Product category was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to '/administrator/menus', notice: 'Product category was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

   def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to '/administrator/menus', notice: 'Product category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.jso

  private

  def menu_item_params
      params.require(:menu_item).permit(:title, :menu_id, :menu_item_id, :title, :link, :position )
  end

  def set_menu
      @menu_item = MenuItem.find(params[:id])
    end

end

app/controllers/administrator/menus_controller.rb
class Administrator::MenusController < AdministratorController
  
   before_action :set_menu, only: [:show, :edit, :update, :destroy]

  def index
    @menus = Menu.all
    render 'administrator/menus/index'
  end

  def edit
    @menu = Menu.find(params[:id])
    render 'administrator/menus/edit'
    end

    def new
    @menu = Menu.new
    
    end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.create(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to '/administrator/menus', notice: 'Product category was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to '/administrator/menus', notice: 'Product category was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.jso

  private

  def menu_params
      params.require(:menu).permit(:title )
  end

  def set_menu
      @menu = Menu.find(params[:id])
    end

end

app/controllers/administrator/orders_controller.rb
class Administrator::OrdersController < AdministratorController

	before_action :set_order, only: [:edit, :destroy, :delete]

	def index
		@orders = Order.all
		render 'administrator/orders/index'
	end

	def edit
		@order = Order.find(params[:id])
  	end

  	def destroy
	    @order = Order.find(params[:id])
	    @order.destroy
	    redirect_to '/administrator/orders'
  	end

  private

  def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type, :total_price, :phone_number, :region, :sity )
  end

  def set_order
      @order = Order.find(params[:id])
    end


end

app/controllers/administrator/post_categories_controller.rb
class Administrator::PostCategoriesController < AdministratorController
  
   before_action :set_post_category, only: [:show, :edit, :update, :destroy]

  def index
    @post_categories = PostCategory.all
    render 'administrator/post_categories/index'
  end

  def edit
    @post_category = PostCategory.find(params[:id])
    render 'administrator/post_categories/edit'
  end

    def new
      @post_category = PostCategory.new
    end

  # POST /product_categories
  # POST /product_categories.json
  def create
    @post_category = PostCategory.new(post_category_params)

    respond_to do |format|
      if @post_category.save
        format.html { redirect_to '/administrator/post_categories', notice: 'Product category was successfully created.' }
        format.json { render :index, status: :created, location: @post_category }
      else
        format.html { render :new }
        format.json { render json: @post_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_categories/1
  # PATCH/PUT /product_categories/1.json
  def update
    respond_to do |format|
      if @post_category.update(post_category_params)
        format.html { redirect_to '/administrator/post_categories', notice: 'Product category was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_category }
      else
        format.html { render :edit }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_categories/1
  # DELETE /product_categories/1.json
  def destroy
    @post_category.destroy
    respond_to do |format|
      format.html { redirect_to '/administrator/post_categories', notice: 'Product category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def post_category_params
      params.require(:post_category).permit(:title, :description,
        :meta_title, :meta_description, :meta_keywords,  :avatar_file_name, :avatar_content_type, :avatar_file_size, :avatar_updated_at,
        :avatar)
  end

  def set_post_category
      @post_category = PostCategory.friendly.find(params[:id])
  end

end

app/views/administrator/static_pages/edit.html.erb
<style type="text/css">
	.tab-content .form-group{
		padding-bottom: 50px;
	}
</style>

<div class="page-content-wrapper">
		<div class="page-content">
			<div class="row">
				<div class="col-md-12">
					<%= form_for([:administrator, @static_page], :multipart => true ) do |f| %>
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption">
									<span class="caption-subject font-blue-madison bold uppercase">
									<%= @static_page.title %> </span>
									<span class="caption-helper">режим редактирования</span>
								</div>
								<div class="actions btn-set">
									<a href="/administrator/post_categories" class="btn btn-default btn-circle"> Назад </a>
									 <%= f.submit(class: "btn blue-madison btn-circle", value: "Обновить") %>
									<!-- <button class="btn green-haze btn-circle">Сохранить</button>
									-->
								</div>
							</div>
							<div class="portlet-body">
								<div class="tabbable">
									<ul class="nav nav-tabs">
										<li class="active">
											<a href="#tab_general" data-toggle="tab">
											Основное </a>
										</li>
										<li >
											<a href="#tab_blocks" data-toggle="tab">
											Блоки </a>
										</li>
										<li>
											<a href="#tab_seo" data-toggle="tab">
											SEO
											</a>
										</li>
									</ul>
									<div class="tab-content no-space">
										<div class="tab-pane active" id="tab_general">
											<div class="form-body">
												<div class="form-group">
													<label class="col-md-2 control-label">Название: </span>
													</label>
													<div class="col-md-10">
														 <%= f.text_field :title, class: "form-control" %>
													</div>
												</div>

												<div class="form-group">
													<label class="col-md-2 control-label">Описание: </span>
													</label>
													<div class="col-md-10">
														 <%= f.cktext_area :content, class: "form-control" %>
													</div>
												</div>

											</div>
										</div>

										<div class="tab-pane" id="tab_blocks">
											<div class="form-body">
												<div class="table-responsive">
											<table class="table table-striped table-hover table-bordered">
											<thead>
											<tr>
												<th>
													 Название
												</th>
												
												<th>
												</th>
											</tr>
											</thead>
											<tbody>
											<% @static_page.site_variables.each do |variable| %>
											<tr>
												<td>
													<a href="#">
													<%= variable.name %></a>
												</td>
												
												<td>
													<a href="<%= edit_administrator_site_variable_path(variable) %>" class="btn default btn-xs green-stripe">
													Редактировать </a>
												</td>
											</tr>
											<% end %>
											</tbody>
											</table>
										</div>
											</div>
										</div>

										<div class="tab-pane" id="tab_seo">
											<div class="form-group">
													<label class="col-md-2 control-label">Title: </span>
													</label>
													<div class="col-md-10">
														 <%= f.text_area :meta_title, class: "form-control" %>
													</div>
												</div>
												<div class="form-group">
													<label class="col-md-2 control-label">Description: </span>
													</label>
													<div class="col-md-10">
														 <%= f.text_area :meta_description, class: "form-control" %>
													</div>
												</div>
												<div class="form-group">
													<label class="col-md-2 control-label">Keywords: </span>
													</label>
													<div class="col-md-10">
														 <%= f.text_area :meta_keywords, class: "form-control" %>
													</div>
												</div>
												</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					<% end %>

				</div>
			</div>
			<!-- END PAGE CONTENT-->
		</div>
	</div>

</div>

app/views/administrator/static_pages/index.html.erb
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- END PAGE BREADCRUMB -->
			<!-- END PAGE HEADER-->
			<!-- BEGIN PAGE CONTENT-->
			<div class="row">
				<div class="col-md-12">
					<% if flash[:notice] %>
					<div id="prefix_262686894761" class="Metronic-alerts alert alert-success fade in"><button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button><%= flash[:notice] %></div>
					<% end %>
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet box blue-madison">
						<div class="portlet-title">
							<div class="caption">
								Все страницы
							</div>
						</div>
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="row">
									<div class="col-md-6">
										<div class="btn-group">
											<a href="/administrator/static_pages/new" id="sample_editable_1_new" class="btn green">Добавить новую</a>
											
										</div>
									</div>
									<div class="col-md-6">
									</div>
								</div>
							</div>
							<table class="table table-striped table-bordered table-hover" id="sample_1">
							<thead>
							<tr>
								<th>
									 id
								</th>

								<th>
									 Название
								</th>
									 
								<th>
									 
								</th>
							</tr>
							</thead>
							<tbody>
							<% @static_pages.each do |static_page| %>
								<tr class="odd gradeX">
									<td>
										 <%=  static_page.id %>
									</td>
									<td>
										 <%= link_to static_page.title, edit_administrator_static_page_path(static_page) %>
									</td>
				
									<td>
										 <%= link_to 'Удалить', administrator_static_page_path(static_page), method: :delete, data: { confirm: 'Удалить ?' } %>
									</td>
								</tr>
							<% end %>
							</tbody>
							</table>

						</div>
					</div>
				</div>
			</div>
				<%= will_paginate @static_pages %>
			<!-- END PAGE CONTENT-->
		</div>
	</div>

app/views/administrator/static_pages/new.html.erb
<style type="text/css">
	.tab-content .form-group{
		padding-bottom: 50px;
	}
</style>

<div class="page-content-wrapper">
		<div class="page-content">
			<div class="row">
				<div class="col-md-12">
					<%= form_for([:administrator, @static_page], :multipart => true ) do |f| %>
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption">
									<span class="caption-subject font-blue-madison bold uppercase">
									Новая страница </span>
									<span class="caption-helper">режим создания</span>
								</div>
								<div class="actions btn-set">
									<a href="/administrator/post_categories" class="btn btn-default btn-circle"> Назад </a>
									 <%= f.submit(class: "btn blue-madison btn-circle", value: "Сохранить") %>
									<!-- <button class="btn green-haze btn-circle">Сохранить</button>
									-->
								</div>
							</div>
							<div class="portlet-body">
								<div class="tabbable">
									<ul class="nav nav-tabs">
										<li class="active">
											<a href="#tab_general" data-toggle="tab">
											Основное </a>
										</li>
										<li >
											<a href="#tab_blocks" data-toggle="tab">
											Блоки </a>
										</li>
										<li>
											<a href="#tab_seo" data-toggle="tab">
											SEO
											</a>
										</li>
									</ul>
									<div class="tab-content no-space">
										<div class="tab-pane active" id="tab_general">
											<div class="form-body">
												<div class="form-group">
													<label class="col-md-2 control-label">Название: </span>
													</label>
													<div class="col-md-10">
														 <%= f.text_field :title, class: "form-control" %>
													</div>
												</div>

												<div class="form-group">
													<label class="col-md-2 control-label">Описание: </span>
													</label>
													<div class="col-md-10">
														 <%= f.cktext_area :content, class: "form-control" %>
													</div>
												</div>

											</div>
										</div>

										<div class="tab-pane" id="tab_blocks">
											<div class="form-body">
												<div class="table-responsive">
											<table class="table table-striped table-hover table-bordered">
											<thead>
											<tr>
												<th>
													 Название
												</th>
												
												<th>
												</th>
											</tr>
											</thead>
											<tbody>
											<% @static_page.site_variables.each do |variable| %>
											<tr>
												<td>
													<a href="#">
													<%= variable.name %></a>
												</td>
												
												<td>
													<a href="<%= edit_administrator_site_variable_path(variable) %>" class="btn default btn-xs green-stripe">
													Редактировать </a>
												</td>
											</tr>
											<% end %>
											</tbody>
											</table>
										</div>
											</div>
										</div>

										<div class="tab-pane" id="tab_seo">
											<div class="form-group">
													<label class="col-md-2 control-label">Title: </span>
													</label>
													<div class="col-md-10">
														 <%= f.text_area :meta_title, class: "form-control" %>
													</div>
												</div>
												<div class="form-group">
													<label class="col-md-2 control-label">Description: </span>
													</label>
													<div class="col-md-10">
														 <%= f.text_area :meta_description, class: "form-control" %>
													</div>
												</div>
												<div class="form-group">
													<label class="col-md-2 control-label">Keywords: </span>
													</label>
													<div class="col-md-10">
														 <%= f.text_area :meta_keywords, class: "form-control" %>
													</div>
												</div>
												</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					<% end %>

				</div>
			</div>
			<!-- END PAGE CONTENT-->
		</div>
	</div>

</div>